/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lomboker.java-library-conventions")
}

dependencies {
    implementation("com.github.javaparser:javaparser-symbol-solver-core:3.19.0")
    implementation("org.apache.commons:commons-lang3:3.6")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}
