/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lomboker.app.getter;

import picocli.CommandLine;
import picocli.CommandLine.Parameters;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import static de.lomboker.lib.GetterReducer.reduceGetters;

public class Getter implements Runnable {

    @Parameters(index = "0")
    File file;

    public static void main(String[] args) {
        int exitCode = new CommandLine(new Getter()).execute(args);
        System.exit(exitCode);
	}

    @Override
    public void run() {
        try {
            String code = Files.readString(file.toPath());
            String converted = reduceGetters(code);
            Files.writeString(file.toPath(), converted);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
