/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lomboker.app;

public class App {
    public static void main(String[] args) {
        System.out.println("nothing implemented yet");
    }
}
